version: '3.9'

services:
    rsshub:
        image: diygod/rsshub:2024-04-17
        container_name: rsshub_main
        restart: unless-stopped
        ports:
            - ${APP_PORT}:1200
        environment:
            TZ: ${TZ}
        env_file:
            - /app-data/rsshub/data/app.env
        networks:
            - tipi_main_network
        depends_on:
            - redis
            - browserless
        labels:
          # Main
          traefik.enable: true
          traefik.http.middlewares.rss-web-redirect.redirectscheme.scheme: https
          traefik.http.services.rsshub.loadbalancer.server.port: 1200
          # Web
          traefik.http.routers.rss-insecure.rule: Host(`${APP_DOMAIN}`)
          traefik.http.routers.rss-insecure.entrypoints: web
          traefik.http.routers.rss-insecure.service: rsshub
          traefik.http.routers.rss-insecure.middlewares: rss-web-redirect
          # Websecure
          traefik.http.routers.rss.rule: Host(`${APP_DOMAIN}`)
          traefik.http.routers.rss.entrypoints: websecure
          traefik.http.routers.rss.service: rsshub
          traefik.http.routers.rss.tls.certresolver: myresolver
          # Local domain
          traefik.http.routers.rss-local-insecure.rule: Host(`rsshub.${LOCAL_DOMAIN}`)
          traefik.http.routers.rss-local-insecure.entrypoints: web
          traefik.http.routers.rss-local-insecure.service: rsshub
          traefik.http.routers.rss-local-insecure.middlewares: rss-web-redirect
          # Local domain secure
          traefik.http.routers.rss-local.rule: Host(`rsshub.${LOCAL_DOMAIN}`)
          traefik.http.routers.rss-local.entrypoints: websecure
          traefik.http.routers.rss-local.service: rsshub
          traefik.http.routers.rss-local.tls: true

    browserless:
        image: browserless/chrome
        container_name: rsshub_browserless
        restart: unless-stopped
        ulimits:
          core:
            hard: 0
            soft: 0
        networks:
            - tipi_main_network

    redis:
        image: redis:alpine
        container_name: rsshub_redis
        restart: unless-stopped
        volumes:
            - ${APP_DATA_DIR}/data/redis:/data
        networks:
            - tipi_main_network
